services:
  map-forge:
    build:
      context: .
      args:
        NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME}
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_SERVICE_ROLE: ${SUPABASE_SERVICE_ROLE}
        SUPABASE_MAP_BUCKET: ${SUPABASE_MAP_BUCKET}
        ACCESS_KEY: ${ACCESS_KEY}
    env_file:
      - .env.local
    ports:
      - "3000:3000"
